---
- name: Install nginx with virtual Hosts
  hosts: webservers
  remote_user: vboxuser
  become: true
  become_method: sudo
  gather_facts: no

  vars:
    sites:
    - "first.com"
    - "second.com"
    - "third.ru"

  roles:
  - nginx-vhosts
